package ru.dimension.db.metadata;

public enum DataType {
  /* Postgres */
  BIT(0, "BIT", DTGroup.BOOLEAN),
  BOOL(1, "BOOL", DTGroup.BOOLEAN),
  CHAR(2, "CHAR", DTGroup.STRING),
  DATE(3, "DATE", DTGroup.DATETIME),
  INT2(4, "INT2", DTGroup.INTEGER),
  INT4(5, "INT4", DTGroup.INTEGER),
  INT8(6, "INT8", DTGroup.INTEGER),
  TEXT(7, "TEXT", DTGroup.STRING),
  TIME(8, "TIME", DTGroup.DATETIME),
  UUID(9, "UUID", DTGroup.STRING),
  BYTEA(10, "BYTEA", DTGroup.BINARY),
  MONEY(11, "MONEY", DTGroup.FLOAT),
  BPCHAR(12, "BPCHAR", DTGroup.STRING),
  FLOAT4(13, "FLOAT4", DTGroup.FLOAT),
  FLOAT8(14, "FLOAT8", DTGroup.FLOAT),
  SERIAL(15, "SERIAL", DTGroup.INTEGER),
  TIMETZ(16, "TIMETZ", DTGroup.DATETIME),
  NUMERIC(17, "NUMERIC", DTGroup.FLOAT),
  VARCHAR(18, "VARCHAR", DTGroup.STRING),
  BIGSERIAL(19, "BIGSERIAL", DTGroup.INTEGER),
  TIMESTAMP(20, "TIMESTAMP", DTGroup.DATETIME),
  SMALLSERIAL(21, "SMALLSERIAL", DTGroup.INTEGER),
  TIMESTAMPTZ(22, "TIMESTAMPTZ", DTGroup.DATETIME),

  /* Oracle */
  RAW(23, "RAW", DTGroup.BINARY),
  CLOB(24, "CLOB", DTGroup.STRING),
  FLOAT(25, "FLOAT", DTGroup.FLOAT),
  NCHAR(26, "NCHAR", DTGroup.STRING),
  NCLOB(27, "NCLOB", DTGroup.STRING),
  NUMBER(28, "NUMBER", DTGroup.FLOAT),
  VARCHAR2(29, "VARCHAR2", DTGroup.STRING),
  NVARCHAR2(30, "NVARCHAR2", DTGroup.STRING),

  /* MS Sql */
  INT(31, "INT", DTGroup.INTEGER),
  REAL(32, "REAL", DTGroup.FLOAT),
  NTEXT(33, "NTEXT", DTGroup.STRING),
  BIGINT(34, "BIGINT", DTGroup.INTEGER),
  BINARY(35, "BINARY", DTGroup.BINARY),
  DECIMAL(36, "DECIMAL", DTGroup.FLOAT),
  SYSNAME(37, "SYSNAME", DTGroup.STRING),
  TINYINT(38, "TINYINT", DTGroup.INTEGER),
  DATETIME(39, "DATETIME", DTGroup.DATETIME),
  NVARCHAR(40, "NVARCHAR", DTGroup.STRING),
  SMALLINT(41, "SMALLINT", DTGroup.INTEGER),
  DATETIME2(42, "DATETIME2", DTGroup.DATETIME),
  VARBINARY(43, "VARBINARY", DTGroup.BINARY),
  SMALLMONEY(44, "SMALLMONEY", DTGroup.FLOAT),
  SMALLDATETIME(45, "SMALLDATETIME", DTGroup.DATETIME),
  UNIQUEIDENTIFIER(46, "UNIQUEIDENTIFIER", DTGroup.STRING),

  /* ClickHouse */
  DEC(47, "DEC", DTGroup.FLOAT),
  BYTE(48, "BYTE", DTGroup.INTEGER),
  ENUM(49, "ENUM", DTGroup.STRING),
  INT1(51, "INT1", DTGroup.INTEGER),
  ENUM8(52, "ENUM8", DTGroup.STRING),
  INT16(53, "INT16", DTGroup.INTEGER),
  INT32(54, "INT32", DTGroup.INTEGER),
  INT64(55, "INT64", DTGroup.INTEGER),
  UINT8(56, "UINT8", DTGroup.INTEGER),
  DATE32(57, "DATE32", DTGroup.DATETIME),
  ENUM16(58, "ENUM16", DTGroup.STRING),
  INT128(59, "INT128", DTGroup.INTEGER),
  INT256(60, "INT256", DTGroup.INTEGER),
  UINT16(61, "UINT16", DTGroup.INTEGER),
  UINT32(62, "UINT32", DTGroup.INTEGER),
  UINT64(63, "UINT64", DTGroup.INTEGER),
  FLOAT32(64, "FLOAT32", DTGroup.FLOAT),
  FLOAT64(65, "FLOAT64", DTGroup.FLOAT),
  BOOLEAN(66, "BOOLEAN", DTGroup.BOOLEAN),
  FIXEDSTRING(67, "FIXEDSTRING", DTGroup.STRING),
  NULLABLE(68, "NULLABLE", DTGroup.STRING),
  IPV4(69, "IPV4", DTGroup.NETWORK),
  IPV6(70, "IPV6", DTGroup.NETWORK),
  ARRAY(71, "ARRAY", DTGroup.ARRAY),
  MAP(72, "MAP", DTGroup.MAP),

  /* Postgres */
  JSONB(73, "JSONB", DTGroup.JSON),
  POINT(74, "POINT", DTGroup.SPATIAL),
  INTERVAL(75, "INTERVAL", DTGroup.INTERVAL),

  /* MySQL */
  SET(76, "SET", DTGroup.SET),

  /* Firebird DB */
  DOUBLE_PRECISION(77, "DOUBLE PRECISION", DTGroup.FLOAT),

  INTEGER(122, "INTEGER", DTGroup.INTEGER),
  OID(123, "OID", DTGroup.INTEGER),
  NAME(124, "NAME", DTGroup.STRING),

  // Java
  LONG(125, "LONG", DTGroup.INTEGER),
  DOUBLE(126, "DOUBLE", DTGroup.FLOAT),
  STRING(127, "STRING", DTGroup.STRING);

  private final byte key;
  private final String value;
  private final DTGroup group;

  DataType(int key, String value, DTGroup group) {
    this.key = (byte) key;
    this.value = value;
    this.group = group;
  }

  public byte getKey() {
    return key;
  }

  public String getValue() {
    return value;
  }

  public DTGroup getGroup() {
    return group;
  }
}